#!/bin/bash

export APP_LITECOIN_NODE_IP="10.21.0.24"

export APP_LITECOIN_RPC_USER="testuser"
export APP_LITECOIN_RPC_PASS="testpass"

export APP_LITECOIN_RPC_PORT=9332

export APP_ELECTRUMX_PUBLIC_CONNECTION_PORT=2344
export APP_ELECTRUMX_NODE_PORT=2346
export APP_ELECTRUMX_LITECOIN_NETWORK="mainnet"
export APP_ELECTRUMX_NODE_IP="10.21.0.99"

