version: '3.7'

services:
  palladiumd:
    image: notrin7/palladiumd:1.3.0
    container_name: palladiumd
    restart: always
    ports:
      - "${PALLADIUM_RPC_PORT}:${PALLADIUM_RPC_PORT}"
      - "${PALLADIUM_P2P_PORT}:${PALLADIUM_P2P_PORT}"
    volumes:
      - ${APP_DATA_DIR}/data:/home/palladium/.palladium