#!/bin/bash

export LITECOIN_RPC_PORT="9332"

export LITECOIN_RPC_USER="testuser"
export LITECOIN_RPC_PASSWORD="testpass"

export LITECOIN_RPC_PORT_1="9332"
export LITECOIN_RPC_PORT_2="9333"
export LITECOIN_DASHBOARD_PORT="10102"

export APP_LITECOIN_NODE_IP="10.21.33.33"
export APP_LITECOIN_FLESK_IP="10.21.33.34"
export APP_LITECOIN_DASHBOARD_IP="10.21.33.35"

export APP_LITECOIN_NODE_IP_2="host.docker.internal"
export APP_LITECOIN_FLESK_IP_2="host.docker.internal"